Repository serai-dex/serai, pull requests merged in 2023-11, with the labels that each got.

#416 Support multiple key shares per validator
  coordinator/src/db.rs
  coordinator/src/main.rs
  coordinator/src/substrate/mod.rs
  coordinator/src/tests/tributary/dkg.rs
  coordinator/src/tests/tributary/mod.rs
  coordinator/src/tests/tributary/tx.rs
  coordinator/src/tributary/db.rs
  coordinator/src/tributary/dkg_confirmer.rs
  coordinator/src/tributary/handle.rs
  coordinator/src/tributary/mod.rs
  coordinator/src/tributary/nonce_decider.rs
  coordinator/tributary/src/lib.rs
  processor/messages/src/lib.rs
  processor/src/key_gen.rs
  processor/src/main.rs
  processor/src/signer.rs
  processor/src/substrate_signer.rs
  processor/src/tests/key_gen.rs
  processor/src/tests/signer.rs
  processor/src/tests/substrate_signer.rs
  substrate/validator-sets/pallet/src/lib.rs
  substrate/validator-sets/primitives/src/lib.rs
  tests/coordinator/src/tests/batch.rs
  tests/coordinator/src/tests/key_gen.rs
  tests/coordinator/src/tests/sign.rs
  tests/processor/src/tests/batch.rs
  tests/processor/src/tests/key_gen.rs
  tests/processor/src/tests/send.rs
Labels: feature, processor, coordinator

#418 Replace `lazy_static` with `once_cell`
  Cargo.lock
  message-queue/Cargo.toml
  message-queue/src/main.rs
  processor/Cargo.toml
  processor/src/networks/bitcoin.rs
  processor/src/tests/mod.rs
Labels: improvement

#427 Route blame between Processor and Coordinator
  coordinator/src/main.rs
  coordinator/src/tests/tributary/mod.rs
  coordinator/src/tributary/db.rs
  coordinator/src/tributary/handle.rs
  coordinator/src/tributary/mod.rs
  coordinator/src/tributary/nonce_decider.rs
  crypto/dkg/src/encryption.rs
  crypto/dkg/src/frost.rs
  crypto/dkg/src/lib.rs
  crypto/dkg/src/promote.rs
  crypto/dkg/src/tests/frost.rs
  crypto/dleq/src/cross_group/mod.rs
  docs/DKG Exclusions.md
  processor/messages/src/lib.rs
  processor/src/key_gen.rs
  processor/src/multisigs/mod.rs
  processor/src/signer.rs
  processor/src/substrate_signer.rs
Labels: feature, processor, coordinator

#442 Remove dtolnay's rust-toolchain action
  .github/actions/build-dependencies/action.yml
  .github/workflows/daily-deny.yml
  .github/workflows/lint.yml
Labels: improvement, CI/CD

#443 Non-intrusive cargo update
  Cargo.lock
Labels: improvement

#452 Replace bincode with borsh
  Cargo.lock
  common/db/src/create_db.rs
  coordinator/Cargo.toml
  coordinator/src/main.rs
  coordinator/src/processors.rs
  coordinator/src/tests/tributary/dkg.rs
  coordinator/src/tributary/handle.rs
  crypto/dkg/Cargo.toml
  crypto/dkg/src/lib.rs
  crypto/multiexp/Cargo.toml
  message-queue/Cargo.toml
  message-queue/src/main.rs
  message-queue/src/messages.rs
  message-queue/src/queue.rs
  processor/Cargo.toml
  processor/messages/Cargo.toml
  processor/messages/src/lib.rs
  processor/src/batch_signer.rs
  processor/src/coordinator.rs
  processor/src/cosigner.rs
  processor/src/multisigs/db.rs
  processor/src/signer.rs
  processor/src/tests/key_gen.rs
  substrate/client/tests/common/in_instructions.rs
  substrate/client/tests/validator_sets.rs
  substrate/coins/pallet/Cargo.toml
  substrate/coins/primitives/Cargo.toml
  substrate/coins/primitives/src/lib.rs
  substrate/in-instructions/pallet/Cargo.toml
  substrate/in-instructions/pallet/src/lib.rs
  substrate/in-instructions/primitives/Cargo.toml
  substrate/in-instructions/primitives/src/lib.rs
  substrate/in-instructions/primitives/src/shorthand.rs
  substrate/node/src/chain_spec.rs
  substrate/primitives/Cargo.toml
  substrate/primitives/src/account.rs
  substrate/primitives/src/amount.rs
  substrate/primitives/src/balance.rs
  substrate/primitives/src/block.rs
  substrate/primitives/src/lib.rs
  substrate/primitives/src/networks.rs
  substrate/validator-sets/primitives/Cargo.toml
  substrate/validator-sets/primitives/src/lib.rs
  tests/coordinator/Cargo.toml
  tests/coordinator/src/lib.rs
  tests/coordinator/src/tests/batch.rs
  tests/coordinator/src/tests/key_gen.rs
  tests/coordinator/src/tests/sign.rs
  tests/processor/Cargo.toml
  tests/processor/src/lib.rs
  tests/processor/src/tests/batch.rs
  tests/processor/src/tests/key_gen.rs
Labels: bug, improvement, processor, coordinator

#454 Move message-queue to a fully binary representation
  Cargo.lock
  coordinator/src/main.rs
  coordinator/src/processors.rs
  coordinator/src/tests/mod.rs
  message-queue/Cargo.toml
  message-queue/src/client.rs
  message-queue/src/main.rs
  message-queue/src/messages.rs
  message-queue/src/queue.rs
  tests/message-queue/src/lib.rs
Labels: improvement

#456 Resolve #360
  Cargo.lock
  common/db/src/create_db.rs
  coordinator/src/db.rs
  coordinator/src/main.rs
  coordinator/src/substrate/db.rs
  coordinator/src/substrate/mod.rs
  coordinator/src/tests/tributary/dkg.rs
  coordinator/src/tributary/db.rs
  coordinator/src/tributary/handle.rs
  message-queue/src/main.rs
  processor/Cargo.toml
  processor/messages/Cargo.toml
  processor/messages/src/lib.rs
  processor/src/batch_signer.rs
  processor/src/cosigner.rs
  processor/src/db.rs
  processor/src/key_gen.rs
  processor/src/main.rs
  processor/src/signer.rs
  processor/src/tests/addresses.rs
  processor/src/tests/batch_signer.rs
  processor/src/tests/cosigner.rs
  processor/src/tests/key_gen.rs
  processor/src/tests/signer.rs
  processor/src/tests/wallet.rs
  tests/coordinator/src/tests/batch.rs
  tests/coordinator/src/tests/key_gen.rs
  tests/coordinator/src/tests/sign.rs
  tests/processor/src/tests/batch.rs
  tests/processor/src/tests/key_gen.rs
  tests/processor/src/tests/send.rs
Labels: improvement, processor

#460 Remove subxt
  Cargo.lock
  coordinator/src/cosign_evaluator.rs
  coordinator/src/main.rs
  coordinator/src/substrate/mod.rs
  coordinator/src/tests/tributary/dkg.rs
  coordinator/src/tributary/scanner.rs
  substrate/client/Cargo.toml
  substrate/client/src/serai/coins.rs
  substrate/client/src/serai/dex.rs
  substrate/client/src/serai/in_instructions.rs
  substrate/client/src/serai/mod.rs
  substrate/client/src/serai/scale_value.rs
  substrate/client/src/serai/validator_sets.rs
  substrate/client/tests/batch.rs
  substrate/client/tests/burn.rs
  substrate/client/tests/common/dex.rs
  substrate/client/tests/common/in_instructions.rs
  substrate/client/tests/common/mod.rs
  substrate/client/tests/common/tx.rs
  substrate/client/tests/common/validator_sets.rs
  substrate/client/tests/dex.rs
  substrate/client/tests/time.rs
  substrate/client/tests/validator_sets.rs
  substrate/in-instructions/pallet/src/lib.rs
  tests/coordinator/src/lib.rs
  tests/coordinator/src/tests/batch.rs
  tests/coordinator/src/tests/key_gen.rs
  tests/coordinator/src/tests/sign.rs
  tests/full-stack/src/lib.rs
  tests/full-stack/src/tests/mint_and_burn.rs
Labels: improvement, client

#462 Use debug builds in our Dockerfiles to reduce CI times
  coins/monero/src/wallet/send/mod.rs
  coordinator/src/p2p.rs
  orchestration/coordinator/Dockerfile
  orchestration/coordinator/Dockerfile.coordinator
  orchestration/message-queue/Dockerfile
  orchestration/message-queue/Dockerfile.message-queue
  orchestration/processor/bitcoin/Dockerfile
  orchestration/processor/bitcoin/Dockerfile.processor.bitcoin
  orchestration/processor/monero/Dockerfile
  orchestration/processor/monero/Dockerfile.processor.monero
  processor/src/main.rs
Labels: improvement, CI/CD

#455 Use parity-db in current Dockerfiles
  Cargo.lock
  common/db/Cargo.toml
  common/db/src/lib.rs
  common/db/src/parity_db.rs
  coordinator/Cargo.toml
  coordinator/src/main.rs
  message-queue/Cargo.toml
  message-queue/src/main.rs
  orchestration/coordinator/Dockerfile
  orchestration/coordinator/Dockerfile.coordinator
  orchestration/message-queue/Dockerfile
  orchestration/message-queue/Dockerfile.message-queue
  orchestration/processor/bitcoin/Dockerfile
  orchestration/processor/bitcoin/Dockerfile.processor.bitcoin
  orchestration/processor/monero/Dockerfile
  orchestration/processor/monero/Dockerfile.processor.monero
  processor/Cargo.toml
  processor/src/main.rs
Labels: improvement, CI/CD
