Repository serai-dex/serai, pull requests merged in 2024-09, with the labels that each got.

#605 Monero v0.18.3.4
  .github/actions/monero-wallet-rpc/action.yml
  .github/actions/monero/action.yml
  .github/actions/test-dependencies/action.yml
  .github/workflows/monero-tests.yaml
  networks/monero/wallet/tests/wallet2_compatibility.rs
  orchestration/dev/networks/monero/hashes-v0.18.3.1.txt
  orchestration/dev/networks/monero/hashes-v0.18.3.4.txt
  orchestration/src/networks/monero.rs
  orchestration/testnet/networks/monero/hashes-v0.18.3.1.txt
  orchestration/testnet/networks/monero/hashes-v0.18.3.4.txt
Labels: improvement, monero, orchestration

#616 Add link for SCALE encoding in doc
  spec/integrations/Instructions.md
Labels: documentation

#617 Constant-time divisors
  Cargo.lock
  crypto/dalek-ff-group/src/field.rs
  crypto/dkg/Cargo.toml
  crypto/dkg/src/evrf/proof.rs
  crypto/evrf/divisors/Cargo.toml
  crypto/evrf/divisors/src/lib.rs
  crypto/evrf/divisors/src/poly.rs
  crypto/evrf/divisors/src/tests/mod.rs
  crypto/evrf/divisors/src/tests/poly.rs
Labels: improvement, cryptography
